version: '3.8'

services:
  mariadb-users:
    image: mariadb:latest
    container_name: mariadb-users
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: userdb
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    ports:
      - "3309:3306"
    volumes:
      - user-data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  mongodb-users:
    image: mongo:latest
    container_name: mongodb-users
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - app-network


  users-service:
    image: kzeta11/user-service:latest
    container_name: users-service
    ports:
      - "50057:50057"  # o el puerto real de tu gRPC
    environment:
      MONGO_DATABASE: mongodb://admin:root@mongodb-users:27017/admin
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - mongodb-users
      - rabbitmq
    networks:
      - app-network

  
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/njs:/etc/nginx/njs:ro
      - ./nginx/postdata.log:/var/nginx/postdata.log
      - ./nginx/ssl/mycert.pem:/etc/nginx/ssl/mycert.pem:ro
      - ./nginx/ssl/mykey.pem:/etc/nginx/ssl/mykey.pem:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

volumes:
  user-data:

networks:
  app-network:
