jobs:
  test_users:
    runs-on: ubuntu-latest

    env:
      USER_SERVICE_URL: "users-service:50057"
      RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672"
      MONGO_DATABASE: "mongodb://admin:root@mongodb-users:27017/admin"

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Levantar contenedores con Docker Compose
        run: docker compose up -d

      - name: Esperar a que users-service esté corriendo
        run: |
          for i in {1..10}; do
            if docker logs users-service 2>&1 | grep -q "Servidor gRPC escuchando"; then
              echo "✅ users-service está arriba"
              exit 0
            fi
            echo "⏳ Esperando a users-service..."
            sleep 3
          done
          echo "❌ users-service no se levantó a tiempo"
          docker compose logs users-service || true
          exit 1

      - name: Ver contenedores activos
        run: docker ps

      - name: Instalar dependencias en API Gateway
        working-directory: ./api
        run: npm install

      - name: Ejecutar pruebas
        working-directory: ./api
        run: npm test

      - name: Apagar contenedores
        if: always()
        run: docker compose down
