name: Test User Service

on:
  push:
    branches:
      - main

jobs:
  test_users:
    runs-on: ubuntu-latest

    env:
      USER_SERVICE_URL: "users-service:50057"
      RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672"
      MONGO_DATABASE: "mongodb://admin:root@mongodb-users:27017/admin"

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Levantar contenedores con Docker Compose
        run: docker compose up -d

      - name: Revisar logs si users-service no está corriendo
        run: |
          if ! docker ps --format '{{.Names}}' | grep -q users-service; then
            echo "❌ users-service no está corriendo. Mostrando logs..."
            docker compose logs users-service || true
            exit 1
          fi

      - name: Esperar a que los servicios estén listos
        run: sleep 20

      - name: Ver contenedores activos
        run: docker ps

      - name: Instalar dependencias en API Gateway
        working-directory: ./api
        run: npm install

      - name: Ejecutar pruebas
        working-directory: ./api
        run: npm test
        env:
          USER_SERVICE_URL: ${{ env.USER_SERVICE_URL }}
          RABBITMQ_URL: ${{ env.RABBITMQ_URL }}
          MONGO_DATABASE: ${{ env.MONGO_DATABASE }}

      - name: Apagar contenedores
        if: always()
        run: docker compose down
